---
#- include:   configure.yml

- name: Build image and with build args
  docker_image:
    name: ben/gerrit:3.0.0
    build:
      path: files/
      args:
        log_volume: /var/log/myapp
        listen_port: 8080
      dockerfile: files/gerritCentosDocfile    
    source: build

