---

- name: Log into DockerHub
  docker_login:
    username: ttserg
    password: '{{ dockerhubpass }}'
  changed_when: False
            

- name: Build image with build args
  docker_image:
    name: ttserg/gerrit:3.0.0
    build:
      dockerfile: gerritCentosDocfile
      path: roles/gerritbuild/files/
      args:
        APP_VER: 3.0.0
#        log_volume: /var/log/myapp
#        listen_port: 8080
    source: build
    push: yes



- name: Log out of DockerHub
  docker_login:
      state: absent

