---
- name: copy script to home/
  copy:
    src: 1postgre.sh
    dest: ~/
  changed_when: False



- name: copy script to home/
  copy:
    src: rmALL.sh
    dest: ~/
  changed_when: False

- name: copy dockerfile to home/
  copy:
    src: postgreUbuntuDocfile
    dest: ~/
  changed_when: False
